### ISSUE TITLE
Tournament Groups 2 "blank page"

### ISSUE THREAD

**Issue by riko105** [andrewwoz/Matcher-iOS-app#10]
* When chained all players with corresponded club, ```Tournament``` "Matches" isn't displayed.
![screen shot 2016-11-28 at 21 57 33](https://cloud.githubusercontent.com/assets/10188785/20684023/f207bbe6-b5b6-11e6-99fb-403794b06a5a.jpg)

* To reproduce bug, choose a "New Competition" button and tap on *Tournament Groups 2 stages* (the last one )icon and choose 16 players.

![screen shot 2016-11-28 at 22 06 49](https://cloud.githubusercontent.com/assets/10188785/20684168/7c33a8ca-b5b7-11e6-825a-f3ebbea4eeeb.jpg)

**Comment by andrewwoz** [comment]
Fixed. Tested.

**Comment by andrewwoz** [comment]
Doesn't work for 32 players Group tournament
